[www]
user = www
group = www

listen = 127.0.0.1:9000
listen.owner = www
listen.group = www

pm = dynamic
pm.max_children = 12
pm.start_servers = 3
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests = 500

catch_workers_output = yes
decorate_workers_output = no

clear_env = no

php_admin_flag[log_errors] = on
access.log = /dev/null
